"""Change VARCHAR to NVARCHAR for Parking

Revision ID: 0c03b393b530
Revises: 5196ff1dbbc1
Create Date: 2025-06-02 17:15:13.247128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c03b393b530'
down_revision: Union[str, None] = '5196ff1dbbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mssql import NVARCHAR

def upgrade():
    op.alter_column("parking", "parking_name",
        existing_type=sa.VARCHAR(length=100),
        type_=NVARCHAR(length=100),
        nullable=True)

    op.alter_column("parking", "address",
        existing_type=sa.TEXT(),  # 또는 sa.VARCHAR, 확인 필요
        type_=NVARCHAR(length=MAX),  # 또는 NVARCHAR(None)
        nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
