"""change to NVARCHAR_20

Revision ID: 31312ec1c053
Revises: c3654465d226
Create Date: 2025-06-02 19:41:51.116698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mssql import NVARCHAR

# revision identifiers, used by Alembic.
revision: str = '31312ec1c053'
down_revision: Union[str, None] = 'c3654465d226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("parking", "external_id",
        existing_type=sa.VARCHAR(length=50),
        type_=NVARCHAR(length=50),
        nullable=True
    )
    op.alter_column("parking", "parking_name",
        existing_type=sa.VARCHAR(length=100),
        type_=NVARCHAR(length=100),
        nullable=True
    )
    op.alter_column("parking", "address",
        existing_type=sa.Text,
        type_=NVARCHAR(length="max"),
        nullable=True
    )
    op.alter_column("parking", "parking_type",
        existing_type=sa.VARCHAR(length=20),
        type_=NVARCHAR(length=20),
        nullable=True
    )
    op.alter_column("parking", "phone_number",
        existing_type=sa.Text,
        type_=NVARCHAR(length="max"),
        nullable=True
    )
    op.alter_column("parking", "operation_type",
        existing_type=sa.VARCHAR(length=50),
        type_=NVARCHAR(length=50),
        nullable=True
    )
    op.alter_column("parking_fee_policy", "weekday_pay_type",
        existing_type=sa.VARCHAR(length=10),
        type_=NVARCHAR(length=10),
        nullable=True
    )
    op.alter_column("parking_fee_policy", "saturday_pay_type",
        existing_type=sa.VARCHAR(length=10),
        type_=NVARCHAR(length=10),
        nullable=True
    )
    op.alter_column("parking_fee_policy", "holiday_pay_type",
        existing_type=sa.VARCHAR(length=10),
        type_=NVARCHAR(length=10),
        nullable=True
    )
    op.alter_column(
        "parking_status",  # 테이블명
        "congestion_level",  # 컬럼명
        existing_type=sa.VARCHAR(length=10),  # 기존 타입
        type_=sa.Unicode(length=10),  # 변경 타입
        nullable=True  # Null 허용 여부에 따라 수정
    )
    op.alter_column(
        "vehicle_table",               # 테이블 이름
        "vehicle_type",                # 컬럼 이름
        existing_type=sa.VARCHAR(length=30),  # 기존 타입
        type_=sa.Unicode(length=30),          # 변경될 타입
        nullable=True                         # 모델 기준 nullable 여부 맞추기
    )
    op.alter_column(
        "vehicle_table",
        "vehicle_type",
        existing_type=sa.Unicode(length=30),
        type_=sa.VARCHAR(length=30),
        nullable=True
    )
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
