"""change to 21

Revision ID: 3fe240145c69
Revises: 529a70df250b
Create Date: 2025-06-02 21:21:24.894631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe240145c69'
down_revision: Union[str, None] = '529a70df250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_table', 'license_plate',
               existing_type=sa.NVARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_table', 'license_plate',
               existing_type=sa.Unicode(length=10),
               type_=sa.NVARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
