"""change favorite

Revision ID: 4baba2769abb
Revises: 680012963b86
Create Date: 2025-06-04 02:02:02.437214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4baba2769abb'
down_revision: Union[str, None] = '680012963b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__user_tabl__favor__7755B73D'), 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'favorite_parking')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('favorite_parking', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__user_tabl__favor__7755B73D'), 'user_table', 'parking', ['favorite_parking'], ['id'])
    # ### end Alembic commands ###
