"""modify OCR_Plate

Revision ID: 51323d642f15
Revises: dc0ef47f2b16
Create Date: 2025-06-02 22:12:15.445027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51323d642f15'
down_revision: Union[str, None] = 'dc0ef47f2b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_record_table', sa.Column('ocr_detected', sa.Unicode(length=15), nullable=False))
    op.add_column('parking_record_table', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('parking_record_table', 'ocr_plate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_record_table', sa.Column('ocr_plate', sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('parking_record_table', 'is_verified')
    op.drop_column('parking_record_table', 'ocr_detected')
    # ### end Alembic commands ###
