"""add column

Revision ID: 5b4b70db445f
Revises: 07bf2f62dab2
Create Date: 2025-06-03 14:58:04.214514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4b70db445f'
down_revision: Union[str, None] = '07bf2f62dab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_usage_table', sa.Column('fee_status', sa.Boolean(), nullable=False))
    op.add_column('user_table', sa.Column('email', sa.String(length=20), nullable=True))
    op.add_column('user_table', sa.Column('favorite_parking', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_table', 'parking', ['favorite_parking'], ['id'])
    op.add_column('vehicle_table', sa.Column('default_type', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_table', 'default_type')
    op.drop_constraint(None, 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'favorite_parking')
    op.drop_column('user_table', 'email')
    op.drop_column('parking_usage_table', 'fee_status')
    # ### end Alembic commands ###
