"""change to log_id

Revision ID: 680012963b86
Revises: 5f3a1d5fea4c
Create Date: 2025-06-04 01:08:12.916845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680012963b86'
down_revision: Union[str, None] = '5f3a1d5fea4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_usage_table', sa.Column('log_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_usage_table', 'log_id')
    # ### end Alembic commands ###
